final changes made to script

diff --git a/a2/directory_cleanup b/a2/directory_cleanup
--- a/a2/directory_cleanup
+++ b/a2/directory_cleanup
@@ -1,34 +1,34 @@
 #!/bin/bash
 
 # Usage function to help user  
-usage() {
+user_usage() {
   echo "Usage: $0 [OPTIONS] <DIRECTORY>"
   echo "USAGE OPTIONS: These are the things you can do! "
   echo "  -e             Condition to delete all empty files (e for empty)"
-  echo "  -o <DAYS>      Condition to delete all old files (default to 30 if no specified amount given)"
-  echo "  -s <SIZE>      Condition to delete all files larger than a certain size (default to 100M)"
-  echo "  -t <TYPE>      Condition to delete all files of a specific type (default txt)"
+  echo "  -o <DAYS>      Condition to delete all old files"
+  echo "  -s <SIZE>      Condition to delete all files larger than a certain size"
+  echo "  -t <TYPE>      Condition to delete all files of a specific type"
   echo "  -a             Condition to delete ALL files in the directory"
   echo "  -h             Condition to display the help message!"
 }
 
 # Different options , variables initialized 
-DELETE_EMPTY=0
-DELETE_OLD=0
-DELETE_SIZE=0
-DELETE_TYPE=0
-DELETE_ALL=0
-OLDER_THAN=0
-SIZE_LIMIT=""
+EMPTY_DEL=0
+OLD_DEL=0
+SIZE_DEL=0
+TYPE_DEL=0
+ALL_DEL=0
+AGE_THRESHOLD=0
+SIZE_THRESHOLD=""
 FILE_TYPE=""
 
 while getopts "eo:s:t:a h" option; do 
   case "$option" in
-    e) DELETE_EMPTY=1 ;;  # Flag to delete empty files
-    o) DELETE_OLD=1; OLDER_THAN=$OPTARG ;;  #Age amount, provided by user 
-    s) DELETE_SIZE=1; SIZE_LIMIT=$OPTARG ;;  #Size amount, provided by user
-    t) DELETE_TYPE=1; FILE_TYPE=$OPTARG ;;  # Delete certain types 
-    a) DELETE_ALL=1 ;;   # Used to delete all files 
+    e) EMPTY_DEL=1 ;;  # Flag to delete empty files
+    o) OLD_DEL=1; AGE_THRESHOLD=$OPTARG ;;  # Age amount, provided by user 
+    s) SIZE_DEL=1; SIZE_THRESHOLD=$OPTARG ;;  # Size amount, provided by user
+    t) TYPE_DEL=1; FILE_TYPE=$OPTARG ;;  # Delete certain types 
+    a) ALL_DEL=1 ;;   # Used to delete all files 
     h) usage; exit 0 ;;  # Success, exit with code 0
     *) usage; exit 1 ;;  # Error, exit with code 1
   esac
@@ -43,45 +43,45 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-TARGET_DIR=$1
+DIRECTORY=$1
 
-#Directory provided, make sure it exists
-if [ ! -d "$TARGET_DIR" ]; then
-  echo "Uh-oh '$TARGET_DIR' does not exist!"
+# Directory provided, make sure it exists
+if [ ! -d "$DIRECTORY" ]; then
+  echo "Uh-oh '$DIRECTORY' does not exist!"
   exit 1
 fi
 
 # Go to directory 
-cd "$TARGET_DIR" || exit
+cd "$DIRECTORY" || exit
 
 #This option deletes all the empty files in the directory if selected
-if [ "$DELETE_EMPTY" -eq 1 ]; then 
+if [ "$EMPTY_DEL" -eq 1 ]; then 
   echo "All files that are empty, are being deleted! "
   find . -type f -empty -exec echo {} \; -exec rm -f {} \;
 fi
 
 #This option deletes files of certain age (older than a certain number of days)
-if [ "$DELETE_OLD" -eq 1 ]; then
-  echo "All files older than $OLDER_THAN days are being deleted!"
-  find . -type f -mtime +$OLDER_THAN -exec echo {} \; -exec rm -f {} \;
+if [ "$OLD_DEL" -eq 1 ]; then
+  echo "All files older than $AGE_THRESHOLD days are being deleted!"
+  find . -type f -mtime +$AGE_THRESHOLD -exec echo {} \; -exec rm -f {} \;
 fi
 
 #This option deletes files of certain sizes in the directory
-if [ "$DELETE_SIZE" -eq 1 ]; then
-  echo "All $SIZE_LIMIT sized files are being deleted!"
-  find . -type f -size +$SIZE_LIMIT -exec echo {} \; -exec rm -f {} \;
+if [ "$SIZE_DEL" -eq 1 ]; then
+  echo "All $SIZE_THRESHOLD sized files are being deleted!"
+  find . -type f -size +$SIZE_THRESHOLD -exec echo {} \; -exec rm -f {} \;
 fi
 
 #This option deletes specific types of files in the directory
-if [ "$DELETE_TYPE" -eq 1 ]; then
+if [ "$TYPE_DEL" -eq 1 ]; then
   echo "All $FILE_TYPE files are being deleted!"
   find . -type f -name "*.$FILE_TYPE" -exec echo {} \; -exec rm -f {} \;
 fi
 
 # This option deletes all the files in the directory if needed 
-if [ "$DELETE_ALL" -eq 1 ]; then
+if [ "$ALL_DEL" -eq 1 ]; then
   echo "ALL files are being deleted!"
   find . -type f -exec echo {} \; -exec rm -f {} \;
 fi
 
-echo "Cleaned Up!"  #end of cleanup indicated via echo 
+echo "Cleaned Up!"  #end of cleanup indicated via echo
